### ISSUE TITLE
Basic Documentation Request

### ISSUE THREAD

**Issue by mccrodp** [coldfrontlabs/fserver#30]
Hi,

From the README.md and help from the issue queue I have been able to install Drupal with FServer. However I do not know how this is supposed to work. 

Can you point me towards documentation or give some basic steps in reply to this issue? I see both developmentseed.org Basic Documentation links from the D6 version of FServer are now broken.

My current questions are currently centered around the following.

<ul>
<li>When I add a new Release Page, there is an issue with referencing projects, looks to be the same as #29 </li>
<li>Generating a Feature at <code>admin/structure/features/page/recreate</code>  I have given my features the "URL of update XML" at http://mysite/fserver. How do I then make this feature available at this location for UPDATE / release info?</li>
<li>When I add Project Page, how does this reference the release? Is "Add New Project" or "Reference Existing Project" related to this?</li>
<li>Can an example of using the release services be provided...</li>
<li>Can an example of the access of project files over http or git using the FServer be provided...</li>
</ul>

The fserver_services module also provides a README stating the following yet /updates/list give 404 - Page not found for me.

<pre>Feature Server Services
=======================

Exposes project update feed using services

Default path is /updates/list</pre>

Thank you for your help. I hope to be able to work with this useful project soon.

Paul.

**Comment by fugazi73** [comment]
That would interest me too much.

Best Regards
Patrick

**Comment by minorOffense** [comment]
Thanks for trying out the module. Here are some answers to help you move forward:

Any of the devseed docs you've seen DO NOT apply to this version. This is a complete rewrite for D7. You're stuck with our README files for now ;-)

Here are some answers for you:

> When I add a new Release Page, there is an issue with referencing projects, looks to be the same as #29 

Should be fixed once we migrate away from ECK.

> Generating a Feature at admin/structure/features/page/recreate I have given my features the "URL of update XML" at http://mysite/fserver. How do I then make this feature available at this location for UPDATE / release info?

Yes, that's where you would put the url. Something like "http://example.com/fserver/release-history". Or you can manually add it to the .info file

``` ini
name = mymodule
core = 7.x
project status url = http://example.com/fserver/release-history
```

> When I add Project Page, how does this reference the release? Is "Add New Project" or "Reference Existing Project" related to this?

The project page node is separate from the project entity. The project page node (node/add/fserver_project_page) is the user facing page with a description of the project, stats, list of releases, that sort of thing.

The Project Entity contains the data related to the project, such as core api version, release files, support majors, that sort of thing.

Have a look at the update XML for a Drupal project (e.g. https://updates.drupal.org/release-history/views/7.x ). Basically, anything you see here is part of the Project Entity. Any data you see at https://drupal.org/project/views which isn't in the update XML would then be part of the project page node.

> Can an example of using the release services be provided...

Look at the fserver.info file. It shows the URL to our soon to be release fserver site.

> Can an example of the access of project files over http or git using the FServer be provided...

If you're fserver is setup and the update XML works, you can use the following with drush to download your module

``` drush
drush dl mymodule --source=http://example.com/fserver/release-history
or
drush up mymodule --source=http://example.com/fserver/release-history
```

If the .info file for a module includes the **project status url** option then with `drush up` you don't need the **--source** part. Look at the fserver.info file for an example.

> The fserver_services module also provides a README stating the following yet /updates/list give 404 - Page not found for me.

Yeah we changed the default path and forgot to update the docs. The path is **fserver/release-history**. I've since updated the README.md file.

Hopefully that helps a bit. Like I said, we have a big change to make to remove ECK which should fix some bugs.
